max_workers: 10

enabled_resources:
  - UnixAccount
  - FTPAccount
  - DBAccount
  - Database
  - WebSite
  - Mailbox

enabled_actions:
  - Create
  - Update
  - Delete

templates_path: ../templates

amqp:
  host: '127.1'
  user: guest
  password: guest
  exchange_type: topic
  connection_attempts: 20
  retry_delay: 3
  heartbeat_interval: 30
  connection_timeout: 5

rest:
  host: '127.1'
  port: 80

mysql:
  host: '127.1'
  user: root
  password: LsMzDpI1QFvK
